<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AssemblyName>hbd</AssemblyName>
        <Company>$(Authors)</Company>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Authors>homebook-io, lk-code</Authors>
        <Description>HomeBook Development CLI and SDK Tools</Description>
        <Copyright>MIT</Copyright>
        <RepositoryUrl>https://github.com/homebook-io/homebook-sdk</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <VersionPrefix>1.0.0</VersionPrefix>

        <PackAsTool>true</PackAsTool>
        <ToolCommandName>hbd</ToolCommandName>

        <PackageId>homebook-sdk</PackageId>
        <PackageProjectUrl>https://github.com/homebook-io/homebook-sdk</PackageProjectUrl>
        <PackageIcon>icon_128.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageOutputPath>./nupkg</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\icon_128.png">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ConsoleAppFramework" Version="5.7.13">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HomeBook.Sdk.Tooling.Core\HomeBook.Sdk.Tooling.Core.csproj"/>
    </ItemGroup>

</Project>
